language: python

python:
  - "2.7"
# No Py3 support for now until a function to .translate() unicode strings is implemented
#  - "3.2"
#  - "3.3"
  - "pypy"

install:
  - pip install -r requirements.txt
  - export PYTHONPATH=.

script:
  - nosetests

notifications:
  email: false
